// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RestArtIS.Server.Models
{
    public partial class ItemPrice
    {
        public Guid ItemPriceId { get; set; }
        public decimal? Value { get; set; }
        public string Currency { get; set; }
        public Guid? VatVid { get; set; }
        public DateTime? ValidFrom { get; set; }
        public DateTime? ValidTo { get; set; }
    }
}