// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RestArtIS.Server.Models
{
    public partial class Menu
    {
        public Guid MenuId { get; set; }
        public string Name { get; set; }
        public short MenuType { get; set; }
        public Guid? ParlorId { get; set; }
        public DateTime? DateFrom { get; set; }
        public DateTime? DateTo { get; set; }
        public DateTime? VisibleFrom { get; set; }
        public DateTime? VisibleTo { get; set; }

        public virtual Parlor Parlor { get; set; }
    }
}