// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RestArtIS.Server.Models
{
    public partial class Parlor
    {
        public Parlor()
        {
            Menu = new HashSet<Menu>();
        }

        public Guid ParlorId { get; set; }
        public Guid? CompanyId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }

        public virtual Company Company { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
    }
}