// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RestArtIS.Server.Models
{
    public partial class PriceCategory
    {
        public Guid PriceCategoryId { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
    }
}