// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RestArtIS.Server.Models
{
    public partial class RestArtItem
    {
        public Guid RestArtItemId { get; set; }
        public string Name { get; set; }
        public string Descrip { get; set; }
        public string Alergens { get; set; }
        public Guid? ItemCategoryId { get; set; }

        public virtual RestArtItemCategory ItemCategory { get; set; }
    }
}