// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace RestArtIS.Server.Models
{
    public partial class RestArtItemCategory
    {
        public RestArtItemCategory()
        {
            RestArtItem = new HashSet<RestArtItem>();
        }

        public Guid RestArtItemCategoryId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<RestArtItem> RestArtItem { get; set; }
    }
}